create table "public"."Subscription" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "stripe_id" text,
    "plan_id" text[],
    "created_at" timestamp with time zone default now()
);


alter table "public"."Subscription" enable row level security;

alter table "public"."CustomerPlans" drop column "plan_id";

alter table "public"."CustomerPlans" add column "email" text;

alter table "public"."CustomerPlans" add column "is_deleted" boolean default false;

alter table "public"."CustomerPlans" add column "phone" text;

alter table "public"."CustomerPlans" add column "stripe_id" text;

alter table "public"."users" add column "phone" text;

CREATE UNIQUE INDEX "Subscription_pkey" ON public."Subscription" USING btree (id);

alter table "public"."Subscription" add constraint "Subscription_pkey" PRIMARY KEY using index "Subscription_pkey";

create policy "Enable insert for authenticated users only"
on "public"."CustomerPlans"
as permissive
for insert
to authenticated
with check (true);



